### PR TITLE
feat/#2: Add community facedetection project

### PR DESCRIPTION
**Pull request by fineanmol**

### CODE REVIEW

**Comment by fineanmol** [comment]
Please merge it and add hacktoberfest-accepted label

**Review by clebsonf — CHANGES_REQUESTED** [review]
The ideal would be a JSON with the title of your project, a link to your repository, an image if you have it and a short description. The goal is to have a screen like this: https://www.octobear.org/programs
(I'm still going to create the awesome repositories screen)

comunity_repositories.json

```JSON
[
   {
        "title": "awesome repository",
        "description" : "awesome description",
        "url" : "https://github.com/fineanmol"
   }
]
```

**Comment by fineanmol** [comment]
@clebsonf I have made the changes. 
I don't have any image for the project, but I have added a reference link for the project

**Review by clebsonf — APPROVED** [review]

**Review by clebsonf — APPROVED** [review]

**Comment by clebsonf** [comment]
closes #2

**Comment by fineanmol** [comment]
Thank you @clebsonf

**Comment by clebsonf** [comment]
@fineanmol Thank you too! By the way, could you give the project one star? This helps to rank and reach new people.

**Comment by fineanmol** [comment]
> @fineanmol Thank you too! By the way, could you give the project one star? This helps to rank and reach new people.

Definitely

**Pull request merged**
