### PR TITLE
feat: display tags of the resource in its card and show all tags available

### PR DESCRIPTION
**Pull request by jrafaaael**
- Show tags of the specific resource in its card
- Show all available tags in `/resources/` page
Screenshot_2022-10-05_16-59-48
Screenshot_2022-10-05_17-01-00

### CODE REVIEW

**Comment by jrafaaael** [comment]
@Gw3i @clebsonf check the design. any recommendation is welcome :+1:

**Comment by Gw3i** [comment]
@jrafaaael  Really greta job! This is how I imagined it 👍 Personally I would go for more decent colours because the tags are really attention grabbing, especially the dark mode. Maybe just borders for the tags? What do you think?

**Comment by jrafaaael** [comment]
@Gw3i sure! Working on this now!

**Comment by jrafaaael** [comment]
@Gw3i what do you think now?
Screenshot_2022-10-05_17-53-20
Screenshot_2022-10-05_17-53-33

**Comment by jrafaaael** [comment]
I closed the PR unintentionally. I open it again

**Comment by jrafaaael** [comment]
I closed the PR unintentionally. I'll open it again with the new commits :)

**Comment by Gw3i** [comment]
@jrafaaael Thanks, looks much better!

**Comment by clebsonf** [comment]
Incredible! This implementation was perfect.

**Pull request merged**
